version: '3'
services:
  server:
    build: .
    command: node src/config/server.js
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"