version: "3"
services:
  gastostracker-app:
    container_name: gastostracker-app
    image: camiloariza/gastostracker-app
    restart: always
    build: .
    ports:
      - "7500:7500"
    links:
      - mongo
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
