name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile

    - name: Deploy to Linode
      env:
        LINODE_API_TOKEN: ${{ secrets.LINODE_API_TOKEN }}
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        sudo mkdir -p /root/.ssh &&
        echo $PRIVATE_KEY > /root/.ssh/private_key.pem
        echo $PUBLIC_KEY > /root/.ssh/private_key.pem.pub    
        echo '${PUBLIC_KEY}' > /root/.ssh/authorized_keys &&
        chmod 600 /root/.ssh/authorized_keys &&
        apt-get update && apt-get upgrade -y &&
        apt-get install -y openssh-server build-essential python &&
        ufw allow ssh &&
        echo "Setting up Linode instance, installing Node.js, and deploying application..."
        ./ci/deploy_linode_nodejs.js
          

