name: Deploy to Linode
on:
  push:
    branches:
      - main

jobs:
  prepare_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        yarn install --frozen-lockfile &&
        mkdir -p ~/.ssh &&
        echo ${PUBLIC_KEY} >> ~/.ssh/authorized_keys
    
    - name: Get Runner IP
      run: echo "::set-env name=RUNNER_IP::$(curl -s https://api.ipify.org)"

    - name: Deploy to Linode
      env:
        LINODE_API_TOKEN: ${{ secrets.LINODE_API_TOKEN }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        RUNNER_IP: ${{ env.RUNNER_IP }}
      run: |
        echo "Setting up Linode instance, installing Node.js, and deploying application..."
        ./ci/deploy_linode_nodejs.js
          

